"""enforce marks for scored assessments

Revision ID: e73d9f382f3a
Revises: 10cd886123db
Create Date: 2026-10-01 23:17:43.133129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73d9f382f3a'
down_revision: Union[str, Sequence[str], None] = '10cd886123db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'chk_assessments_scored_marks',
        'assessments',
        "status != 'scored' OR marks IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_assessments_scored_marks', 'assessments', type_='check')
    # ### end Alembic commands ###
